[package]
name = "undo_stack"
description = "A minimal undo stack for user defined types"
repository = "https://github.com/chipmusic/undo_stack"
version = "0.1.8"
edition = "2021"
license = "MIT"


[workspace]
members = ["example", "example_group"]


[features]
std = []
