[package]
name = "undo_stack"
description = "A minimal undo stack for user defined types"
# repository = ""
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
